MCU = atmega32u4
BOOTLOADER = caterina
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = yes
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes

ENCODER_MAP_ENABLE = no

RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = bitbang
